# Generated by Django 6.1 on 2026-08-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('ADMIN', 'Admin')], default='ORGANIZATION', max_length=20, verbose_name='User role'),
        ),
    ]
