# Generated by Django 6.1 on 2026-08-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سمینار / کنفرانس')),
                ('date_held', models.DateTimeField(verbose_name='تاریخ برگزاری')),
                ('description', models.TextField(verbose_name='توضیحات رویداد')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ثبت\u200cنام')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل برگزاری')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='consultants.consultant', verbose_name='سخنران / مدرس')),
            ],
            options={
                'verbose_name': 'رویداد / سمینار',
                'verbose_name_plural': 'سمینارها و کنفرانس\u200cها',
                'ordering': ['-date_held'],
            },
        ),
    ]
