# Generated by Django 6.1 on 2026-09-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام سازمان / شرکت')),
                ('contact_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('business_industry', models.CharField(max_length=100, verbose_name='حوزه فعالیت')),
                ('contact_role', models.CharField(max_length=100, verbose_name='سمت درخواست\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام رویداد',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای رویدادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
