# Generated by Django 6.1 on 2026-08-17 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سمینار / کنفرانس')),
                ('date_held', models.DateTimeField(verbose_name='تاریخ برگزاری')),
                ('description', models.TextField(verbose_name='توضیحات رویداد')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='consultants.consultant', verbose_name='سخنران / مدرس')),
            ],
            options={
                'verbose_name': 'رویداد / سمینار',
                'verbose_name_plural': 'سمینارها و کنفرانس\u200cها',
            },
        ),
    ]
