# Generated by Django 6.1 on 2026-08-17 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان شغلی / تخصص اصلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی و رزومه')),
                ('experience_years', models.IntegerField(default=0, verbose_name='سابقه کار (سال)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='لینک عکس مشاور')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاوران',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیحات خدمت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات مشاوره',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سمینار / کنفرانس')),
                ('date_held', models.CharField(max_length=100, verbose_name='تاریخ برگزاری')),
                ('description', models.TextField(verbose_name='توضیحات رویداد')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultant', verbose_name='سخنران / مدرس')),
            ],
            options={
                'verbose_name': 'رویداد / سمینار',
                'verbose_name_plural': 'سمینارها و کنفرانس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام سازمان / شرکت')),
                ('description', models.TextField(verbose_name='شرح نیاز و عارضه\u200cهای سازمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('preferred_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultant', verbose_name='مشاور پیشنهادی (اختیاری)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست\u200cدهنده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecategory', verbose_name='نوع خدمت مورد نیاز')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
            },
        ),
    ]
