# Generated by Django 6.1 on 2026-08-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان شغلی / تخصص اصلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سابقه کار (سال)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='لینک عکس')),
                ('is_verified', models.BooleanField(default=False, verbose_name='مشاور تایید شده')),
                ('response_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='زمان پاسخگویی')),
                ('projects_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پروژه\u200cها')),
                ('companies_count', models.PositiveIntegerField(default=0, verbose_name='تعداد شرکت\u200cهای مشاوره داده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاوران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گواهینامه')),
                ('issuer', models.CharField(max_length=200, verbose_name='صادرکننده')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهینامه')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='لینک مدرک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='consultants.consultant', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_available', models.BooleanField(default=True, verbose_name='فعال')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='consultants.consultant', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'زمان دسترسی مشاور',
                'verbose_name_plural': 'زمان\u200cهای دسترسی مشاوران',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('video_url', models.URLField(verbose_name='لینک ویدیو')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='لینک تصویر ویدیو')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='consultants.consultant', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'ویدیو مشاور',
                'verbose_name_plural': 'ویدیوهای مشاوران',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
