# Generated by Django 6.1 on 2026-08-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان شغلی / تخصص اصلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی و رزومه')),
                ('experience_years', models.IntegerField(default=0, verbose_name='سابقه کار (سال)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='لینک عکس مشاور')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاوران',
            },
        ),
    ]
