# Generated by Django 6.1 on 2026-08-17 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام سازمان / شرکت')),
                ('description', models.TextField(verbose_name='شرح نیاز و عارضه\u200cهای سازمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('preferred_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='consultants.consultant', verbose_name='مشاور پیشنهادی')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='services.servicecategory', verbose_name='نوع خدمت مورد نیاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
            },
        ),
    ]
