# Generated by Django 6.1 on 2026-09-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='حوزه کسب\u200cوکار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حوزه کسب\u200cوکار',
                'verbose_name_plural': 'حوزه\u200cهای کسب\u200cوکار',
            },
        ),
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='سمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سمت درخواست\u200cدهنده',
                'verbose_name_plural': 'سمت\u200cهای درخواست\u200cدهنده',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام سازمان / شرکت')),
                ('contact_name', models.CharField(max_length=100, verbose_name='نام درخواست\u200cدهنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('business_industry', models.CharField(choices=[('IT', 'فناوری اطلاعات'), ('MANUFACTURING', 'تولیدی'), ('FOOD', 'صنایع غذایی'), ('PHARMA', 'دارویی'), ('FINANCE', 'مالی و بانکی'), ('CONSTRUCTION', 'ساختمان و عمران'), ('OTHER', 'سایر')], max_length=30, verbose_name='حوزه فعالیت')),
                ('contact_role', models.CharField(choices=[('CEO', 'مدیرعامل'), ('CEO_OFFICE', 'دفتر مدیرعامل'), ('HR', 'مدیر منابع انسانی'), ('FINANCE', 'مدیر مالی'), ('IT_MANAGER', 'مدیر فناوری اطلاعات'), ('OTHER', 'سایر')], max_length=30, verbose_name='سمت درخواست\u200cدهنده')),
                ('description', models.TextField(verbose_name='شرح نیاز و عارضه\u200cهای سازمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('consultant_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='consultants.consultantservice', verbose_name='خدمت و مشاور انتخاب\u200cشده')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='services.servicecategory', verbose_name='خدمت مورد نظر')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
